#!/bin/sh
set -e

VER="2.1.0"

if [ "$1" = "configure" ]; then
	update-alternatives --install /usr/bin/bowtie2-align bowtie2-align /usr/bin/bowtie2-align${VER} 10
	update-alternatives --install /usr/bin/bowtie2-inspect bowtie2-inspect /usr/bin/bowtie2-inspect${VER} 10
	update-alternatives --install /usr/bin/bowtie2-build bowtie2-build /usr/bin/bowtie2-build${VER} 10
	update-alternatives --install /usr/bin/bowtie2 bowtie2 /usr/bin/bowtie2${VER} 10
fi
